### ISSUE TITLE
generate the tracking results and plots

### ISSUE THREAD

**Issue by 872473172** [JoshuaRWaite/Shooter_Tracking#1]
Thank you for contributing! Do you keep looping when you finally generate the tracking results and plots? Or is something wrong with me somewhere else?

**Comment by JoshuaRWaite** [comment]
You're welcome, and thank you for your interest in it!

The scripts to generate tracking results loop over different confidence thresholds and the available weights, which takes a while, but you should be able to see progress in the console and evaluation_results folder. Is that what you're experiencing, or is a different part looping and getting stuck?

**Comment by 872473172** [comment]
![2024-03-17 13-08-45 的屏幕截图](https://github.com/JoshuaRWaite/Shooter_Tracking/assets/43776724/5ae7cde3-3005-4c34-945a-cf4cef6dada0)
Thanks for the reply! This is the case in my evaluation_results folder and I don't know where to find the problem?

**Comment by 872473172** [comment]
Thanks for the reply! This is the case in my evaluation_results folder and I don't know where to find the problem?
![2024-03-17 13-12-04 的屏幕截图](https://github.com/JoshuaRWaite/Shooter_Tracking/assets/43776724/65837342-ffea-433b-96c0-5e69627c1b4a)

**Comment by 872473172** [comment]
I don't seem to have spent enough time generating enough txt results, does this file contain files that can directly specify weights and data to generate trace results? I don't seem to see any description in either the code or the paper. Looking forward to hearing from you!

**Comment by JoshuaRWaite** [comment]
You're welcome!

I think the issue is an invalid file path. Tracking_results.sh works in two main steps. The first is to generate the tracking outputs with track.py. Then the tracking outputs are compared with the ground truth (MOT-ASTERS/train/MOT-ASTERS-0X/gt) using the motmetrics Python package to compute the metrics.

I forgot to specify where to put the inference videos, so for simplicity, I added them directly to this repo with the last push. Running the shell script should now find the videos to generate the tracking outputs correctly, and then compute the MOT metrics.

Hopefully, this helps fix the issue. Let me know if you need any more assistance!

**Comment by 872473172** [comment]
> 别客气！
> 
> 我认为问题是无效的文件路径。Tracking_results.sh主要分为两个步骤。第一种是用 track.py 生成跟踪输出。然后，使用 motmetrics Python 包将跟踪输出与地面实况 （MOT-ASTERS/train/MOT-ASTERS-0X/gt） 进行比较，以计算指标。
> 
> 我忘了指定将推理视频放在哪里，所以为了简单起见，我在最后一次推送时将它们直接添加到这个存储库中。现在，运行 shell 脚本应该会找到视频以正确生成跟踪输出，然后计算 MOT 指标。
> 
> 希望这有助于解决问题。如果您需要更多帮助，请告诉我！

Thank you for the recovery, about the video question I have finished generating the video using the images in the dataset, the previous problem may be that there is not enough time to iterate through all the results generated, if I want to directly use your model and weights to detect a new video, what should I do?

**Comment by 872473172** [comment]
<img width="543" alt="image" src="https://github.com/JoshuaRWaite/Shooter_Tracking/assets/43776724/498f0fc3-88af-4e2a-a530-f6594996d3f0">
I want to use your model to track different video objects with different weights, so as to achieve a similar effect in your paper. If you can, please have a relevant explanation.

**Comment by JoshuaRWaite** [comment]
You can use this line to run inference with your desired parameters

python examples/track.py --save-mot --yolo-model "$model_weight" --source "inference/videos/${video}" --name "exp_${model_name}_video${video%.*}_conf_gun${conf_gun}_conf${conf}" --device 0 --conf_gun "$conf_gun" --conf "$conf" --project Tracking_Outputs --tracking-method deepocsort_confirm

For example,

python examples/track.py --save-mot --yolo-model "yolov8n_AugCTextured_CMasked_Real_S.pt" --source "inference/videos/example.mp4" --name "test" --device 0 --conf_gun 0.8 --conf 0.6 --project Tracking_Outputs --tracking-method deepocsort_confirm

Would detect and track shooters using gun confirmation in the example.mp4 video. If you want to also save the video output with bounding boxes, you can add --save and if you want to see the video with bounding boxes as it's running, you can add --show

If you want to compute the metrics, you will need to label the video(s) using a tool like cvat (https://github.com/opencv/cvat) to have the ground truth, which can be a tedious process.

If you want to detect and track objects other than shooters, https://github.com/mikel-brostrom/yolo_tracking would probably be better suited for the task. It's the project I built upon to add the confirmation step to track ID initialization. Alternatively, using custom weights and changing --tracking-method to just deepocsort in this repo should work the same.

Also, just to be clear, I manually added the red arrows in the tracking image to represent the time component of tracking. The video output just has the bounding boxes with ID and confidence.

Hopefully this helps, let me know if you have any more questions!

**Comment by 872473172** [comment]
Thank you for your answer, I have solved the problem of reasoning, after filtering out the 11 weights you bolded in your paper, I reasoned about the same video, and I think that yolov8n_AugCTextured_CMasked_Real_S(The missed detection rate is low), yolov8n_AugCTextured_CMasked_Real_M, and yolov8n_AugCTextured_CMasked_Real_S (Low false detection rate)have the best effect, and finally I have the problem that the guns mentioned in your paper are difficult to detect, and maybe adding some fires generated when bullets are fired may be helpful for gun detection, I wish you all the best in your work!

**Comment by JoshuaRWaite** [comment]
You're welcome, glad you were able to get it working! That's an interesting idea, although one thing to consider is that detecting the gun when it's already being fired is probably later than ideal. Nonetheless, having higher confidence in gun detection would still be good. I considered adding more annotated guns to the real data from existing gun datasets, but class imbalance might become a concern. Thank you!
